---
Gemfile:
  optional:
    ':development, :unit_tests':
      - gem: 'puppetlabs_spec_helper'
        github: 'justinstoller/puppetlabs_spec_helper'
        branch: 'compute_version'
      - gem: 'puppet-blacksmith'
        github: 'justinstoller/puppet-blacksmith'
        branch: 'env_vars_for_forge'
